jobs:
    build:
      docker:
        - image: sillelien/circleci-dollar-build-image

      environment:
        MAJOR_VERSION: 0.1
        MAVEN_OPTS: "-Xmx1g -DbuildNumber=${CIRCLE_BUILD_NUM} -Dorg.xml.sax.driver='com.sun.org.apache.xerces.internal.parsers.SAXParser' "
        TZ: "/usr/share/zoneinfo/Europe/London"

      working_directory: ~/github-api

      branches:
        ignore:
          - gh-pages

      steps:

        - checkout

        - restore_cache:
            key: dependency-cache

        - run:
            name: dependencies
            command: |
              ~/build-utils/maven_make_deps.sh
                  
        - save_cache:
            key: dependency-cache
            paths:
                - ~/.m2
        - run:
            name: test
            command: |
              echo "login=neilellis" > ~/.github
              echo "password=${GITHUB_PASSWORD}" >> ~/.github
                 mvn -q -Drat.skip -Dsource.skip=true -DgenerateReports=false -Dmaven.javadoc.skip=true install
            no_output_timeout: 600

        - deploy:
            command: |
              if [ "${CIRCLE_BRANCH}" == "staging" ]; then
                      ~/build-utils/promote_from_staging.sh
              fi
              if [ "${CIRCLE_BRANCH}" == "master" ]; then
                      ~/build-utils/maven_deploy.sh
              fi
