jobs:
    build:
      docker:
        - image: sillelien/circleci-dollar-build-image

      environment:
        MAJOR_VERSION: 0.1
        MAVEN_OPTS: "-Xmx1g -DbuildNumber=${CIRCLE_BUILD_NUM}  "
        TZ: "/usr/share/zoneinfo/Europe/London"

      working_directory: ~/github-api

      branches:
        ignore:
          - gh-pages

      steps:

        - checkout

        - restore_cache:
            key: dependency-cache

        - run:
            name: init
            command: /home/circleci/.build-init.sh

        - run:
            name: dependencies
            command: |
              ~/build-utils/maven_make_deps.sh


        - run:
            name: test
            command: |
              echo "login=neilellis" > ~/.github
              echo "password=${GITHUB_PASSWORD}" >> ~/.github
              git config --global --unset url."ssh://git@github.com".insteadOf "https://github.com" || true
              mvn -Drat.skip -Dsource.skip=true -DgenerateReports=false -Dmaven.javadoc.skip=true clean install
              git config --global url."ssh://git@github.com".insteadOf "https://github.com" || true

            no_output_timeout: 600

        - save_cache:
            key: dependency-cache
            paths:
                - ~/.m2
        - deploy:
            command: |
              if [ "${CIRCLE_BRANCH}" == "staging" ]; then
                      ~/build-utils/promote_from_staging.sh
              fi
              if [ "${CIRCLE_BRANCH}" == "master" ]; then
                      ~/build-utils/maven_deploy.sh
              fi
